### ISSUE TITLE
Size of the centroid point

### ISSUE THREAD

**Issue by Ateamate** [IDEMSInternational/conflict-forecast-content#6]
We need to be able to determine or set the size of the centroid points based on the 'centroid_size_sum' and 'centroid_size_mean' properties of the centroid data as shown in the image below.
![image](https://github.com/user-attachments/assets/1489d39f-3471-4607-ab84-ba09819dc84c)

We have noted that the 'centroid_size_sum' are points to be plotted on the total population map and 'centroid_size_mean' are points on the population density map

**Comment by jfmcquade** [comment]
Closed by https://github.com/IDEMSInternational/open-app-builder/pull/2457/

**Comment by jfmcquade** [comment]
Closed by https://github.com/IDEMSInternational/open-app-builder/pull/2457/
